#!/bin/sh
set -e

# If EmonMUC is installed, set device template permissions
if [ -d /var/opt/emonmuc ]; then
    emonuser=$(ls -ld /var/opt/emonmuc | awk '{print $3}')
    chown emonuser:emonuser -R /var/opt/ems/dev
fi

#DEBHELPER#

# Start service if still idle
if ! systemctl is-active --quiet openmuc; then
    systemctl start openmuc
fi

exit 0
